language: node_js
node_js:
- '0.12'

env:
  global:
  - GH_REF=github.com/procurement-analytics/procurement-analytics.git
  - DEPLOY_BRANCH=master
  - secure: "gg07LMj5Xah+/+MAsEcIk3YI3LGtjd11mjene6zhzbgREYsZpS/eLz44aY/p6xNheTeJg66Z22kyZRStXgZ7Rlb0uenYjHIIl57/Quk2XJ6IJ+Jwci18HCgLR0muhD6y8gmf8kUBTnyWmlbu1f1w82KQyuTs/WhQ2YHn/0N2hJs="

before_install:
- chmod +x ./.build_scripts/deploy.sh

script:
- gulp prod

after_success:
- ./.build_scripts/deploy.sh
  